### ISSUE TITLE
Install fails when login to postgres

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/codimd_ynh#15]
On an up-to-date VPS, latest Yunohost version, install fails.

After these two steps:
> sudo --login --user=postgres PGUSER=postgres  PGPASSWORD=Something  psql codimd
sudo --login --user=postgres dropdb codimd

I get: 
> FATAL:  terminating connection due to administrator command
 WARNING server closed the connection unexpectedly
 WARNING   This probably means the server terminated abnormally
 WARNING   before or while processing the request.
 WARNING connection to server was lost

**Comment by alexAubin** [comment]
Hmmm do you still reproduce this ?

**Comment by lapineige** [comment]
No, thanks to #19 😃
