### ISSUE TITLE
Dreaming about it <3

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost-Apps/codimd_ynh#16]
We'd love so much to see it working here at @mailtape for our YH instance <3
Could you share any news on your side regarding shipping please?

kisskiss

**Comment by lapineige** [comment]
Well, the news are simple: install fails (at least on my side), I don't know how to fix this.
I need some help from people that have better knowledge in this area (installing codimd, postgres stuff) to help fix this.

If you wanna share that need for help and ask for help, you're welcome to do it ;)

**Comment by lapineige** [comment]
#19 should have fixed it :)
