### ISSUE TITLE
Upgrade to 1.6

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/codimd_ynh#18]
CodiMD version 1.6 is out https://github.com/codimd/server/releases/tag/1.6.0

PR welcome :)

**Comment by Lab-8916100448256** [comment]
Hi,
Please have a look at the PR : https://github.com/YunoHost-Apps/codimd_ynh/pull/19
:)

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost-Apps/codimd_ynh/pull/19
