### ISSUE TITLE
Add YunoHost package installation in codimd setup doc

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/codimd_ynh#35]
As proposed by @SISheogorath

https://github.com/YunoHost-Apps/codimd_ynh/pull/31#pullrequestreview-430244902

We should add informations for codimed_ynh doing a PR on https://github.com/codimd/server/tree/master/docs/setup

**Comment by sy6sy2** [comment]
Hi, I guess you choose the wrong name for the citation 😉

**Comment by lapineige** [comment]
@SylvainCecchetto where's the fun in using good names and so on ? :D

**Comment by ericgaspar** [comment]
I made a PR to CodiMD upstream about deploying CodiMD with YunoHost.
https://github.com/codimd/server/pull/431

**Comment by ericgaspar** [comment]
Closing this issue. #431 is merged into master.
