### ISSUE TITLE
On upgrade: Unhandled rejection SequelizeConnectionError: password authentication failed for user "codimd" 

### ISSUE THREAD

**Issue by nin0-0** [YunoHost-Apps/codimd_ynh#36]
**Versions**
- Hardware: *Dedicated*
- YunoHost version: 4.0.2
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *yes*
- If yes, please explain: Installed testing first with yunohost install app <url>
- Using, or trying to install package version/branch: testing
- If upgrading, current package version: 1.6.0~ynh2

**To Reproduce**
*Steps to reproduce the behavior.*
- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app upgrade codimd -u https://github.com/YunoHost-Apps/codimd_ynh.git
    ```
**Expected behavior**
App upgraded and working

**Logs**
```Warning: Jun 21 11:11:40 npm[29455]: Unhandled rejection SequelizeConnectionError: password authentication failed for user "codimd"
Warning: Jun 21 11:11:40 npm[29455]:     at connection.connect.err (/var/www/codimd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)
Warning: Jun 21 11:11:40 npm[29455]:     at Connection.connectingErrorHandler (/var/www/codimd/node_modules/pg/lib/client.js:194:14)
Warning: Jun 21 11:11:40 npm[29455]:     at Connection.emit (events.js:198:13)
Warning: Jun 21 11:11:40 npm[29455]:     at Socket.<anonymous> (/var/www/codimd/node_modules/pg/lib/connection.js:134:12)
Warning: Jun 21 11:11:40 npm[29455]:     at Socket.emit (events.js:198:13)
Warning: Jun 21 11:11:40 npm[29455]:     at addChunk (_stream_readable.js:288:12)
Warning: Jun 21 11:11:40 npm[29455]:     at readableAddChunk (_stream_readable.js:269:11)
Warning: Jun 21 11:11:40 npm[29455]:     at Socket.Readable.push (_stream_readable.js:224:10)
Warning: Jun 21 11:11:40 npm[29455]:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by ericgaspar** [comment]
@nin0-0 As this is a complete rewriting of the install / remove /restore / upgrade / backup scripts... Upgrading from the previous app script (which was at level one) may not work. I will advise you to remove and make a fresh install.

**Comment by ericgaspar** [comment]
@nin0-0 Don't really know what's going wrong here.
can you try to upgrade from the current PR ?
`sudo yunohost app upgrade codimd -u https://github.com/ericgaspar/codimd_ynh/tree/patch`

**Comment by nin0-0** [comment]
Yeah it's pretty unclear to me too, I'm gonna just reinstall and close the issue, since it was testing branch

I tried upgrading that way already, but the codimd user auth error remains. It's just unclear to me where npm authenticated with this user.

Thanks for looking anyway !
