### ISSUE TITLE
Installation fails : Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by matthias4217** [YunoHost-Apps/codimd_ynh#42]
**Describe the bug**

CodiMD installation fails with `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
If I understand correctly, the VPS I'm on just lacks ram. I've kept an eye on `htop` during installation and the 1GB ram got filled, and I think at least part of the swap too. 

**Versions**
- Hardware: *Online VPS*, 1GB Ram and 256MB swap
- YunoHost version: 3.8.4.9
- I have access to my server: Through SSH and through the Yunohost webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
- Using, or trying to install package version/branch: Trying to install CodiMD 1.6.0~ynh3

**To Reproduce**
Either from the webadmin or via ssh :
- ```sh
    sudo yunohost app install codimd
    ```

**Expected behavior**
I hoped the installation would work fine. ^^

**Logs**
*If applicable and useful, add screenshots to help explain your problem.*

Full logs here : https://paste.yunohost.org/raw/inekuxewob

**Comment by ericgaspar** [comment]
@matthias4217 1GB of Ram may not be enough. I believe CodiMD needs at least 2 GB of RAM...
