### ISSUE TITLE
config.json is overwritten by update

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/codimd_ynh#46]
**Describe the bug**

When updating the application, `/var/www/codimd/config.json` is overwritten, despite the [README file](https://github.com/YunoHost-Apps/codimd_ynh#configuration) which invites to tweak it.

**Versions**
- Hardware: Old laptop or computer
- YunoHost version: 4.0.8
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *yes*
  - If yes, please explain: I changed the value of **tooBusyLag** because I ofter get a *I'm busy right now, try again later.* message otherwise.
- Using, or trying to install package version/branch: 1.6.0~ynh4
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info codimd`*

**To Reproduce**

1. Get an old version of Codimd.
1. Add in `/var/www/codimd/config.json` and in the "production"` section the following line:  `"tooBusyLag": 10000,`
1. Restart the service in order to see the change
1. Upgrade Codimd
1. Check the content of the `/var/www/codimd/config.json` file

**Expected behavior**
You should see the  `"tooBusyLag": 10000,` line in the above file

**Actual behavior**
The line has disappeared.

**Comment by lapineige** [comment]
I don't really know how other Yunohost package manage that (ping @YunoHost-Apps/apps-group) appart from making a backup and letting you manually transfer the changes if you want to (I do that for Pixelfed, it's painful, but at least my changes are not lost).

**Comment by fflorent** [comment]
As a workaround to this issue, you may create a empty file with env variables (maybe with just a comment to explain how to fill it) and source it when running codimd. So the user can only tweak the file with env variable and the app maintainer may tweak the `config.json` file at his/her convenience.

If I quote [this page](https://github.com/codimd/server/blob/master/docs/configuration.md#configuration):
> Environment variables take precedence over configurations from the config files. They generally start with CMD_ for our own options, but we also list node-specific options you can configure this way.

**Comment by ericgaspar** [comment]
@fflorent  This upgraded version of CodiMD allows installation in a sub-folder, therefore the config.json file has a new `$path` argument hence the choice to overwrite the previous config.json file. Not ideal I guess...

**Comment by fflorent** [comment]
Useful link for sourcing an environment file in a systemd service:

https://fedoraproject.org/wiki/Packaging:Systemd#EnvironmentFiles_and_support_for_.2Fetc.2Fsysconfig_files

**Comment by yalh76** [comment]
> 
> 
> **Describe the bug**
> 
> When updating the application, `/var/www/codimd/config.json` is overwritten, despite the [README file](https://github.com/YunoHost-Apps/codimd_ynh#configuration) which invites to tweak it.

Yes it's a normal behavior, it's why during upgrade, there is :
https://github.com/YunoHost-Apps/codimd_ynh/blob/58e85a9edda5b6a90dfb06b25a5534f1f07ff648/scripts/upgrade#L140

`ynh_backup_if_checksum_is_different` keep a copy of the the config file to let you tweak again :)
