### ISSUE TITLE
Change the tooBusyLag value by default

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/codimd_ynh#47]
**Describe the bug**
The default [`tooBusyLag`](https://github.com/codimd/server/blob/master/docs/configuration.md#codimd-basics) value is a bit low (70ms). On my server (old computer), I get the * I'm busy right now, try again later* message very often, which is a bit annoying.

Even if that value can be tweaked, what to do you think increasing it by default? (I don't know, to `10000` if that's not too high)

**Versions**
- Hardware: *Old laptop or computer*

**Comment by lapineige** [comment]
What does that value change ?
Is this the lag between server and client, or the server time-to-answer a request ?

If that's the second case, I'm ok to increase it, as many people that will self-host this won't have a lot of users, hence it wouldonly be annoying and not useful to reduce server load.

**Comment by fflorent** [comment]
> What does that value change ?

The detail is explained here: https://www.npmjs.com/package/toobusy-js

So it is rather this answer:

> the server time-to-answer a request

To be fair, I am not sure what is a good value for this setting. Is it 100ms? 1000ms? 10000ms?
I would say `1000` might be enough.

**Comment by lapineige** [comment]
I'd go for 1 second, it should be fairly enough in any normal condition.

Yet I have no time to add that change myself. If you can, feel free to submit a pull request

**Comment by fflorent** [comment]
Sounds wise!

**Comment by fflorent** [comment]
> If you can, feel free to submit a pull request

Sure!
