### ISSUE TITLE
Installation fails due to corrupt source (sha256sum)

### ISSUE THREAD

**Issue by pintman** [YunoHost-Apps/codimd_ynh#51]
**Describe the bug**
Installation fails

**Versions**
- Hardware: Hetzner, VPS
- YunoHost version: 4.0.8.2
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no 
- Using, or trying to install package version/branch: codimd

**To Reproduce**
Just install the package.

**Expected behavior**
Installed codimd.

**Logs**
https://paste.yunohost.org/raw/aqilepuluy

**Comment by ericgaspar** [comment]
@pintman Thanks for reporting this issue.
CodiMD project goes through a name change process: from **CodiMD** to **HedgeDoc**. The name of the downloaded file changed from *codimd-1.6.0.tar.gz* to *hedgedoc-1.6.0.tar.gz*: the shasum no longer matches the signature...
this will be corrected shortly.

**Comment by ericgaspar** [comment]
Should be fixed with #52

**Comment by pintman** [comment]
I am one step further. Thank for the fast support.

But now the setup fails as well with a different kind of error. It looks like a timeout during build of node modules.

The log is here: https://paste.yunohost.org/raw/danoqacuyu

**Comment by ericgaspar** [comment]
@pintman I don't know how much ram you have available on your VPS... CodiMD needs a massive 3.5GO of RAM to buid the app...

**Comment by pintman** [comment]
That might be the problem. Thanks for the fast answer. I can increase the amount of RAM for the installation process. However is this big amount of RAM needed in production as well?

**Comment by ericgaspar** [comment]
Indeed it is massive. I hope in the future they will provide prebuid binaries

**Comment by pintman** [comment]
I did an installation with an 8 GB machine. After installation I scaled down back to 1 GB. Everything worked fine so far. 

Thanks for your help.
