### ISSUE TITLE
Transitionning from CodiMD to HedgeDoc.

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/codimd_ynh#55]
A new version 1.7 is coming soon... It is about time to transition this repo.
To do so I have created a new repo : https://github.com/YunoHost-Apps/hedgedoc_ynh that should be good to go as far as naming and links...
@kay0u pointed out the use of a [Helper script](https://github.com/YunoHost-Apps/Experimental_helpers/tree/master/ynh_handle_app_migration) to migrate files and database from CodiMD to HedgeDoc.
I am wondering if it is worth the effort to implement this...

**Comment by lapineige** [comment]
Ok, then maybe I was a bit too hasty with this PR #54 …

**Comment by Jaxom99** [comment]
Hi, is there a good migration path from codi_ynh to hedgedocs_ynh ? Is a DB dump/restore enough ?

**Comment by ericgaspar** [comment]
I dont know so I asked about it in the HedgeDoc Matrix room ... Here is the answer:
> don't know if it's still that simple, but yes, it seems for quite a long time this worked. Not sure it still does
https://community.hedgedoc.org/t/my-experience-migrating-from-hackmdio-codimd-to-hedgedoc/245

**Comment by Jaxom99** [comment]
Great, thank you ! I'll let you know how it goes.

EDIT : it *kind of* worked. I had to `sed` codimd to Hedgedoc in the dump, to allow the new app to use the database. One thing lost is the upload files (like images) : they are stored in the `/var/www/codimd/public/upload` , so i should have copied them over.

So the path seems easy :

1. Export files
2. Dump the codimd PG database
3. Remove codimd app
4. Install hedgedoc app in same domain/path
5. Stop the service and drop the new hedgedoc PG database
6. sed the database dump for `s/codimd/hedgedoc/g`
5. Create new database 'hedgedoc" and import the modified dump
6. Copy files over
7. Restart hedgedoc service :smile:

**Comment by lapineige** [comment]
@Jaxom99 

> I had to sed codimd to Hedgedoc in the dump

How do you do that ?

Could you please explain a little further how you do each individual step  ?
In particular:
1) In which format ?
6) how do you "sed" it ? What's the command syntax ?
7) how can we do it ? Any specific parameters ?

Additional question : is the history kept ?
Thank in advance ! :)
