### ISSUE TITLE
App does not backup uploaded files :sweat:  

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/codimd_ynh#66]
Hi,

I know this app is deprecated for hedgedoc, but as the repo is open, I still want to point out an (old) bug :wink: 

It turns out the backups don't include images that are uploaded in the "./public/upload" folder of the app. So after a restore (or the upgrade to hedgedoc), the notes are missing their images, even if the [img] reference is still present in the edit section of the note.

I can provide config details and logs as needed.

Thanks for your feedback, and maybe the issue will be transferred to https://github.com/YunoHost-Apps/hedgedoc_ynh ?

**Comment by ericgaspar** [comment]
This package is still alive... (cf. https://github.com/YunoHost-Apps/codimd_ynh/issues/44#issuecomment-835323143) it is now using the original CodiMD sources... (the fork, aka Hedgedoc, as now his own repo). I must admit that is very confusing 🙃

As for your uploaded images, that is strange... the app backup the entire CodiMD folder; that includes `./public/upload` folder. I don't know what caused this file to be empty...

**Comment by Jaxom99** [comment]
Okay thanks for clarifying ;) 

The folder is indeed present in the backup, but empty. And the operation log has disappeared. So much for me :/
