### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/codimd_ynh#8]
Install fails with this error:
> npm install
WARNING npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
WARNING npm WARN deprecated uws@0.14.5: New code is available at github.com/uNetworking/uWebSockets.js
WARNING npm WARN deprecated to-markdown@3.1.1: to-markdown has been renamed to Turndown, with a new API. Please update to turndown v4.0.0 or above and see the migration guide for details: https://github.com/domchristie/turndown/wiki/Migrating-from-to-markdown-to-Turndown

There are additional messages after those ones (I think it's npm error during the uninstall, because of uncomplete install), I can provide them if needed.

**Comment by lapineige** [comment]
And with the testing version:

> DEBUG - /var/www/codimd /var/cache/yunohost/from_file/codimd_ynh-testing/scripts
 DEBUG - + npm install
DEBUG - + ynh_exit_properly
WARNING - npm ERR! Linux 4.15.18-10-pve
DEBUG - + local exit_code=1
WARNING - npm ERR! argv "/opt/node_n/n/versions/node/6.17.1/bin/node" "/opt/node_n/n/versions/node/6/bin/npm" "install"
 DEBUG - + '[' 1 -eq 0 ']'
 WARNING - npm ERR! node v6.17.1
 DEBUG - + trap '' EXIT
 WARNING - npm ERR! npm  v3.10.10
 DEBUG - + set +eu
WARNING - npm ERR! code ETARGET
DEBUG - + echo -e '!!\n  codimd'\''s script has encountered an error. Its execution was cancelled.\n!!'

**Comment by anmol26s** [comment]
same error

**Comment by alexAubin** [comment]
Fixed in recent commits.

(Still, be careful anyway with this app, it's not to be considered as stable)
