### ISSUE TITLE
Install failure on arm64 due to PhantomJS dependency

### ISSUE THREAD

**Issue by EmpressFiona** [YunoHost-Apps/codimd_ynh#82]
### Describe the bug

Installing CodiMD fails on arm64 due to a dependency that isn't distributed in the architecture (specifically PhantomJS).

### Context

- Hardware: arm64 VPS
- YunoHost version: 11.0.10.1
- I have access to my server: Through SSH and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: Running under LXD on a VPS. This shouldn't have any impact on the bug though, it's an issue with the npm package.
- Using, or trying to install package version/branch: 2.4.2~ynh1

### Steps to reproduce

Should happen on any arm64 install (ie, `sudo yunohost app install codimd`). This doesn't happen with HedgeDoc, which installs just fine (and which I didn't know about until looking into related issues).

### Logs

Provided here: https://paste.yunohost.org/raw/ekazakugis

It should be noted that [PhantomJS has never supplied prebuilt arm64 binaries](https://github.com/Medium/phantomjs/issues/577). Therefore, either it'll need to be built in the script or an alternate binary will need to be found. (Or, instead, this app would be retired and replaced with HedgeDoc...)

**Comment by ericgaspar** [comment]
fixed with #83
